version: '3.8'

services:

  prod_web:
    image: pszdldocker/stonkstracker
    ports:
    - '80'
    working_dir: "/stonksomatic/src"
    command: "gunicorn --bind 0.0.0.0:80 algo_trading_monitor.wsgi:server"
    restart: 'always'

  dev_web:
    image: pszdldocker/stonkstracker
    build:
      dockerfile: docker/dash.dockerfile
      context: .
    ports:
      - '8050:8050'
    command: "python /stonksomatic/src/algo_trading_monitor/application.py"

  rev_proxy:
    image: "nginx:latest"
    ports:
    - '80:80'
    depends_on:
      - prod_web
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf"
    restart: always